import Head from 'next/head'
import {Search} from "../components/Search";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Open Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex justify-center items-center">
          <div>
            <h1 className="text-2xl">OpenSearch</h1>
            <Search />
          </div>
      </main>
    </div>
  )
}
